<div class="modal-dialog " role="document" style="max-width: 1000px;">
                        <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Terms and Agreement</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body terms-agreements pl-5 pr-5">
                            <p><strong>SERVICES AGREEMENT<br></strong></p>
                            <table align="left" cellpadding="0" cellspacing="0" hspace="0" vspace="0">
                                <tbody>
                                    <tr>
                                    <td align="left" valign="top">
                                        I understand that NEAC (Medical Exams Application Center, Inc.) as a separate entity from NCSBN, U.S. Nursing Boards and other countries’ authorized licensing institutions, credential evaluators and exam coordinators. I choose NEAC to facilitate my exam application processing by filling out the forms for me, preparing the application, securing a money draft and mailing materials to the related institutions in chosen country(ies). I further acknowledge that NEAC cannot be held responsible for the loss of applications, wrong information provided on the application by the applicant and money drafts, finger print cards or any other items collected or mailed to complete the application process; nor from slow processing or non-processing of the documents by subject organizations or lost documents in mail or any loss due to computer-based glitches. I am responsible to check the prepared application thoroughly for any typos or wrong information before it is sent out. All the forms must carry my official name (not my nickname) as it appears on my government issued Identity Cards such as Passport or I may not be admitted to the exam due to name mismatch.<br><br>
                                        I, the undersigned, voluntarily make and grant this Waiver of Liability and Assumption of Risk in favor of NEAC as partial consideration (in addition to monies paid to the N.E.A.C) for the opportunity to use the facilities, equipment, know-how, materials and/or other assets of the NEAC to process my exam application(s); and/or to receive assistance, training, guidance and/or instructions from the personnel of the NEAC. <u>I do hereby authorize NEAC agents or employees,</u> <b><i>act as my representative on all processing related matters for all phases,</i></b> <u>including qualification phases and the actual Licensing and also after for endorsement or renewal with the selected country.</u> I <u>also authorize them to</u> <b><i><u>receive and open email, mail, phone calls on my behalf. I choose to use NEAC office address and email address as my contact address</u></i></b> to enable NEAC to communicate for me with related organizations. I understand that NEAC may not be able to communicate with related organizations in my behalf, If I decide to use my own address on applications. By signing below, I allow NEAC to disclose confidential, personal, private information about my file at NEAC to any person(s); I release and indemnify NEAC, its members, trustees, officers and employees from any liability for losses, damages or claims of any type arising out of actions taken by NEAC in reliance upon this Authorization. This Authorization will remain valid for three (3) years from the date written below (or if none, from the date this Authorization is received by NEAC). Be advised NEAC's <b><u>main communication mean is email and send important notices via email. Applicants to avail NEAC services must have an active email address</u></b> (if not avail one from free email service providers). <b><u>The applicant should check their emails on a daily basis for the notices that NEAC will send. NEAC will not be responsible for missed deadlines, expired documents, eligibility, ATT or rejections caused by applicants' failure to check their emails.</u></b> Applicant must inform NEAC if there is any change in their contact information and email address. <u>However, it is still applicants’ responsibility to contact NEAC to follow up their applications if not heard from NEAC more than a month.</u><br><br>
                                        I understand that I will be provided an express mail (DHL or FEDEX) tracking number, money draft serial/reference number and my application may be sent individually or together with other applications that are going to the same Board of Nursing. However, NEAC does not have any control on how the related institutions will send their documents or letters to the applicant. Some related institutions send their letters via regular mail which may take weeks to receive. I hereby waive and release any and all claims whether in contract or for personal damage, damages, losses and delays. NEAC and its staff may suggest or advise me on NCLEX eligibility application related topics which may affect my choices and decisions, however, I understand that I cannot hold NEAC or its staff responsible for their advice even if I encounter any problems as a result. I understand that every state has different endorsement/reciprocity requirements and I may or may not be able to endorse my license other states. I am the one choosing the state which I am applying to and my decision is based on my own judgement. I will not hold NEAC responsible from my decisions. I also authorize NEAC to charge the related fees to my credit card or provide my credit card information to related institutions and have them charge related fees to my credit card if I decide to use my own credit card. <b><u>NEAC only provides me a fingerprint card and is not responsible from rejected fingerprint cards since most of the rejections are due to local authorities' poor finger print collecting.</u></b> Fingerprint cards are not for sale. There may be charges for <b>additional</b> finger print cards supplied to the applicant due to the mailing cost from the States to the Philippines. Digitally signing the documents and forms means filling them out and submitting to NEAC via their site, mobile app or email etc.  <br><br>
                                        <b>You hereby accept that your contact information may be shared with third party organizations</b> for marketing, referral or lead generation purposes. <br><br>
                                        NEAC makes follow-up calls to the related institutions after the usual processing time, if there is a problem with your application. However, these organizations sometimes do not answer calls, reply to emails, fax or mail inquiries due to the high volume of applicants. NEAC offers only 2 separate attempts a week for 4 weeks using one of the communication options mentioned above. If respondent party doesn't reply to NEAC after all these attempts NEAC has the right not to continue with the follow up and will be considered as having provided follow up services regardless the status of application is completed or pending. <u>Requests for exam schedule changes must be submitted at least 1 week prior.</u> <b>Processing time of your application starts from the time your requirements have been submitted to the</b> required institution <b>and depends on the volume of the applications they have. Processing time also may differ from one applicant to another based on many variables. You may receive your eligibility less or more than an estimated time and sooner or later than someone who applied together with you. <u>Applicants must complete and submit the required documents within two (2) years of signing this agreement or the application will be destroyed and all fees will be forfeited. If the applicant wants to continue their application he or she must therefore pay all required fees again including the NEAC service fee.</u></b> I also recognize that my hiring of NEAC for follow-up purposes does not entitle <b><u>me to getting the contact details which NEAC uses to work on my behalf nor does it entitle me to being taught methods and procedures which NEAC uses to prepare documents and correct errors.</u></b><br><br>
                                        <b>Collected service fees are non-refundable. Service fees are not transferable to other services and other persons. NEAC service fees do not include <u>TOR</u> mailing cost. <u>DO NOT PAY CASH in NEAC Centers</u> except for ‘NEAC Service fees’. Fees other than ‘NEAC services fees’ must be deposited to the NEAC Bank accounts provided to you. If you have been asked to pay in cash any other fees please report it to</b> feedback@applynclex.com. In case of Philippines Peso currency payment, the equivalent peso value shalldepend on the day when deposit is being made and it is determined by XE.com Inc. (an independent 3rd party) exchange rate plus NEAC's ‘<b>1.10</b>' mark up. <br><br>
                                        <b>Promos and Discounts</b>: Promo down payments paid expire after 1 year. An applicant can benefit only from one promo, promos cannot be combined. Applicants referred by affiliated Review Centers must purchase one of the PPP (Payment Protection Plan) to avail a Promo. Gift Checks and promos can't be combined. <u>To avail any of NEAC's promos a PPP must be purchased.</u><br><br>
                                        <b>Acknowledgement Receipt or Official Receipt</b>: The <i>Acknowledgement Receipt and Bank Deposit Slips</i> you have received serves as PROOF of PAYMENT. This receipt needs to be presented to the NEAC officers when requested. Payments cannot be verified without the Acknowledgement Receipt and you may have to pay the required fees again if you fail to furnish the proof of payment which is your acknowledgement receipt. <br><br>
                                        <b><i>*'Approval Guaranteed or Money Back' (Refund) Policy</i></b>: If a related institution rejects for ANY reason OTHER than credential evaluation, accreditation, not authentic supporting documents, and NEAC's follow ups with the related institution but can't resolve the problem within 90 days then NEAC guarantees to return the total amount of ‘<i>Application Fees and the NEAC Service Fee</i>’ collected to the applicant within 30 days. <u>A letter from Board of Nursing or related institutions stating missing document or incomplete application does not mean your application has been rejected and is not ground for a refund.</u> Due to up to 1-year processing time of some Boards of Nursing, NEAC should be allowed 1 year to secure a eligibility upon completion of all required documents by the applicant. If NEAC cannot secure the eligibility within 1 year then the applicant can avail a full refund. Unless you request in written to cancel your application to a Board, NEAC will continue processing your application. Board of Nursing or other related organizations have deadlines and NEAC tries hard to meet these deadlines; therefore, it is very important that the applicant follows NEAC's instructions and submits the documents required in timely manner. NEAC is not responsible for the applicant's failure to provide required documents and materials. Other fees collected are not refundable and are not included in this offer. <br><br>
                                        <b>Additional Services (optional):</b><br><br>
                                        <b><i>Payment Protection Plan</i></b> (PPP) is a plan that protects NEAC applicants from any type of financial losses that may occur during the processing of their NCLEX Eligibility Application and or Credential Evaluation Services based on the plan chosen. It has been reported by some NCLEX applicants that some State Board of Nursing have lost their payments and don't want to take any responsibility of it. This has been the case even if the applicant has provided a proof of payment. In this type of situation applicant can actually take his or her complaints to Board's management however usually it is very difficult or get hold of someone and wait for any reply from the management in a timely manner. It is also possible that money draft may be lost by the carrier. Either way the applicant is in a position to make another payment in the same amount, pay the money draft assistance fee and spend additional express mailing fee to send the payment to the Board of Nursing again. This will also slow down the application process. Even though this type of problem does not take place very often, NEAC's Payment Protection Plan protects applicants from possible losses and gives peace of mind. With this Payment Protection Plan, applicants will be protected up to P40,000 in losses. Which means in case of any of those above described incidents occur NEAC will be the one making the necessary payments to the related departments immediately so that the application can be filed successfully and the processing continues in full speed. In the meantime, NEAC will be communicating to the related departments to recover the lost payment(s) if recoverable. In case third party organizations who received the payment agree to credit or refund any overpayments, the refund will be sent directly to the applicant. When the applicant receives a refund, he or she agrees to pay it back to NEAC within 7 working days. <br><br>
                                        Also, Payment Protection Plan <u>can ONLY be availed before an application is sent out.</u> A Payment Protection Plan availed AFTER the application was sent out is not a valid PPP and won't be honored by NEAC management. The acknowledgement receipt of PPP must carry an earlier date then the application mailing date or PPP payment will be refunded to the applicant. This plan does not cover applications that are affected from natural disasters or war. If you choose to avail this plan you <u>MUST use NEAC office address in your applications</u> as your address so we can do follow ups on your behalf. <i>To benefit from this plan, you MUST present this agreement together with your acknowledgement receipt</i>.<br><br>
                                        <b>FORM3 SERVAGGR 04262018revEA08172018</b><br><br>
                                        NEAC fees are subject to taxes of certain countries and cities. <br><br>
                                        <b>I have read all the Agreement, all the forms NEAC has provided to me I understand and accept all the terms above.</b><br><br>
                                        <b>Site Usage Agreement</b><br><br>
                                        NEAC Medical Exams Center Inc.®, its parent, subsidiaries and affiliated companies, (collectively "NEAC Medical Exams Center Inc.") maintain this site (the "Site") to provide information about the NEAC Medical Exams Center Inc. Certification programs. Your access to and use of the Site is subject to the following terms and conditions ("Terms and Conditions") and all applicable laws. By accessing and browsing the Site, you accept, without limitation or qualification, these Terms and Conditions which may be modified from time to time. You may review the most current version of the Terms and Conditions at any time at www.medexamcetner.com. Any new features that augment or enhance the current Site shall be subject to the Terms and Conditions. If you do not agree to these Terms and Conditions, please do not use the Site. <br><br>
                                        <b>NEAC Medical Exams Center Inc.'s Proprietary Rights</b><br><br>
                                        You should assume that everything you see or read on the Site is protected by all copyright, patent, trademark and other laws relating to the protection of proprietary rights unless otherwise noted, and may not be used except as provided in these Terms and Conditions without the express written permission of NEAC Medical Exams Center Inc.. You acknowledge and agree that the Site and any necessary software used in connection with the Site ("Software"), all images, photography, regardless of source, graphics, artwork, text, Marks as defined elsewhere in these Terms and Conditions, and other information and material found on the Site and all intellectual property relating thereto ("Licensed Content"), is owned by NEAC Medical Exams Center Inc. or its parent, subsidiaries or affiliates or its suppliers and contains proprietary and confidential information that is protected by applicable intellectual property and other laws. Subject to compliance with the Terms and Conditions of this Agreement, NEAC Medical Exams Center Inc. grants to you a restricted, nonexclusive, non-transferable, non-sublicenseable license to use the Site and Software solely as follows: <br><br>
                                        To access the Licensed Content and Software from the Site solely for your use. You may not relicense, rent or lease the Software or use the Software for third-party training, commercial time-sharing or service bureau use or processing data of any other entity. <br><br>
                                        You may not sell, distribute, transfer, modify, copy, transmit, create derivative works, modify or publish the Licensed Content, with or without consideration, or use the Licensed Content to compete with NEAC Medical Exams Center Inc. or create your own website for use by others based on or containing the Licensed Content that is accessible to third parties. You are authorized to view, but not download (other than as necessary to view), reproduce or use, any Licensed Content found on any portion of the Site. This Agreement shall automatically terminate if you breach any provision of this license and such breach is not cured within ten (10) days of notice of the breach. You agree not to cause or permit the reverse engineering, disassembly or decompilation of the Software. NEAC Medical Exams Center Inc. grants no rights other than those granted explicitly herein and hereby reserves and retains all worldwide title, copyright and other proprietary rights in the, Site and Software, including all updates and modifications thereto. <br><br>
                                        You further acknowledge and agree that material contained in sponsor advertisements or information presented to you through the Site or advertisers is protected by copyrights, trademarks, service marks, patents or other proprietary rights and laws. Except as expressly authorized by NEAC Medical Exams Center Inc., you agree not to modify, rent, lease, loan, sell, distribute or create derivative works based on the Site or on the Software, in whole or in part. <br><br>
                                        <b>Privacy</b>
                                        NEAC Medical Exams Center Inc. values its relationship with visitors and therefore makes every effort to safeguard personal information while also making information available to our visitors. NEAC Medical Exams Center Inc. collects personal information in several ways from different parts of the Site, for example if you were to ask a question or report a problem with the Site. If you contact NEAC Medical Exams Center Inc., we may keep a record of that session or correspondence. NEAC Medical Exams Center Inc. may also occasionally ask users to complete surveys for research purposes. At present, NEAC Medical Exams Center Inc. does not require registration, however in the event registration is instituted, personal information such as name, address, telephone and facsimile number, billing and credit card or other account information, would be gathered just as if you telephoned or contacted NEAC Medical Exams Center Inc. via facsimile or regular mail. <br><br>
                                        By transmitting any information, suggestions, material or other content to NEAC Medical Exams Center Inc. , you automatically grant NEAC Medical Exams Center Inc. the royalty-free, perpetual, irrevocable, non-exclusive right and license to use, reproduce, modify, adapt, publish, translate, distribute and display such information, suggestions, material or other content.   <br><br>
                                        NEAC Medical Exams Center Inc. may use "cookies" to secure your transaction activities and enhance the performance of the Site. A cookie is a small amount of identifier data that is sent to your browser from a NEAC Medical Exams Center Inc. web server and stored on your computer's hard drive. Generally, NEAC Medical Exams Center Inc. may use cookies to: (a) remind it of who you are in order to deliver to you a better and more personalized service and (b) estimate its audience size. By determining the nature and extent of repeat usage, NEAC Medical Exams Center Inc. will be able to (c) target information to you based upon your interests; and (d) measure certain traffic patterns to understand how users' habits are similar or different from one another, all so that NEAC Medical Exams Center Inc. may improve the Site. NEAC Medical Exams Center Inc. also collects IP addresses for system administration to include them in outgoing mail message headers. NEAC Medical Exams Center Inc. may also research its users' demographics, interests and behavior based on the information provided upon registration, during a promotion, from its server log files or from servers, to better understand its users. To help us improve its services to you, NEAC Medical Exams Center Inc. may, from time to time, make collective customer information available to selected third parties, but only in the aggregate. As a rule, NEAC Medical Exams Center Inc. will not disclose any of your personally identifiable information. However, by accessing and using the Site, you agree that such information may be disclosed as described above, in addition to when NEAC Medical Exams Center Inc. has reason to believe that disclosing this information is necessary to identify, contact or bring legal action to enforce any of NEAC Medical Exams Center Inc.'s rights, including against you or a third party for nonpayment, or violation of the Terms and Conditions causing injury to or interference with its rights or property, to other NEAC Medical Exams Center Inc. users or anyone else that could be harmed by such activities. NEAC Medical Exams Center Inc. may disclose or access account information when NEAC Medical Exams Center Inc. believes in good faith that the law requires it and for administrative and other purposes that NEAC Medical Exams Center Inc. deems necessary to maintain, service and improve our products and services and to protect our rights or property. <br><br>
                                        <b>Subscriber Conduct</b><br><br>
                                        You understand that all information, data, messages or other materials transmitted are the sole responsibility of the person from whom such material originated. This means that you and not NEAC Medical Exams Center Inc. are entirely responsible for all uploads and/or emails transmitted via the Site. Under no circumstances will NEAC Medical Exams Center Inc. be liable in any way for your use of any Licensed Content, including but not limited to any errors or omissions in any Licensed Content or for any loss or damage of any kind incurred as a result of the use of any Licensed Content emailed or otherwise transmitted via the Site. <br><br>
                                        You agree to not use the Site to: <br><br>
                                        (a) email or otherwise transmit anything that is unlawful, harmful, threatening, abusive, harassing, tortuous, defamatory, vulgar, obscene, libelous, invasive of another's privacy, hateful or racially, ethnically or otherwise objectionable; <br>
                                        (b) impersonate any person or entity or falsely state or otherwise misrepresent your affiliation with a person or entity; <br>
                                        (c) forge headers or otherwise manipulate identifiers in order to disguise the origin of anything transmitted through the Site; <br>
                                        (d) email or otherwise transmit anything that you do not have a right to transmit under any law or under contractual or fiduciary relationships (such as inside information, proprietary and confidential information learned or disclosed as part of employment relationships or under nondisclosure agreements);
                                        (e) email or otherwise transmit anything that infringes any patent, trademark, trade secret, copyright or other proprietary right ("Rights") of any party; <br>
                                        (f) email or otherwise transmit any unsolicited or unauthorized advertising or promotional materials; <br>
                                        (g) email or otherwise transmit any material containing software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software, hardware or telecommunications equipment; <br>
                                        (h) interfere with or disrupt the servers or networks connected to the Site or disobey any requirements, procedures, policies or regulations of networks connected to the Site; <br>
                                        (i) intentionally or unintentionally violate any applicable local, state, national or international law, rules or regulations; <br><br>
                                        <b>Indemnity</b><br><br>
                                        By accessing and using the Site, you agree to indemnify and hold NEAC Medical Exams Center Inc., its parent, subsidiaries, affiliates, advisory board, certification board, officers, suppliers, co-branders or other partners, agents and employees, harmless from any claim or demand, including reasonable attorneys' fees, due to or arising out of anything you submit or transmit through the Site, your use of the Site, your connection to the Site, your violation of the Terms and Conditions, or your violation of any Rights. <br><br>
                                        <b>Modifications to the Site</b><br><br>
                                        NEAC Medical Exams Center Inc. reserves the right at any time and from time to time to modify or discontinue, temporarily or permanently, the Site (or any part thereof) or the Licensed Content or may terminate your use of this Site with or without notice. You agree that NEAC Medical Exams Center Inc. shall not be liable to you or to any third party for any modification, suspension or discontinuance of the Site. NEAC Medical Exams Center Inc. has no obligation and assumes no duty to revise or update the Site (or any part thereof) or any Licensed Content placed on the Site, even if new information regarding the NEAC Medical Exams Center Inc. program, the status of persons or business entities certified by NEAC Medical Exams Center Inc. or other Licensed Content becomes available for disclosure. <br><br>
                                        <b>Dealings with Advertisers</b><br><br>
                                        Your correspondence or business dealings with any persons or business entities certified by NEAC Medical Exams Center Inc., or participation in promotions of sponsors, partners, advertisers or other third parties found on or through the Site, if any, including payment and delivery of related goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such third party. NEAC Medical Exams Center Inc. specifically disclaims any obligation to review, test or otherwise confirm the accuracy of any information placed on the Site or otherwise obtained from such sponsors, partners, advertisers or other third parties. NEAC Medical Exams Center Inc. also specifically disclaims any duty or obligation to revise the Site (or any part thereof) or any Licensed Content in connection with any changes in federal, state or local laws or regulations. You agree that NEAC Medical Exams Center Inc. shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings or as the result of the presence of such third parties on the Site. However we may be privy to and use personal information provided by you to such parties. <br><br>
                                        <b>Links</b><br><br>
                                        The Site may contain links to third party WorldWide Websites or resources. Because NEAC Medical Exams Center Inc. has no control over such sites and resources, you acknowledge and agree that NEAC Medical Exams Center Inc. is not responsible for the availability of such external sites or resources, and does not endorse and is not responsible or liable for any products or other materials on or available from such sites or resources. <br><br>
                                        <b>NEAC Medical Exams Center Inc. Certification</b><br><br>
                                        NEAC Medical Exams Center Inc. makes no representations or warranties that any person or business entity listed in this website and used by you to provide products or services will meet your needs and expectations. <br><br>
                                        <b>Notice</b><br><br>
                                        Notices to you may be made via either email or regular mail. Notice or other correspondence to NEAC Medical Exams Center Inc. should be mailed to: <br><br>
                                        Healthcare Licensing Application Center /NEAC<br>
                                        22820 NE 64th St<br>
                                        Redmond, WA 98053 USA<br><br>
                                        <b>Trademark Information</b><br><br>
                                        NEAC Medical Exams Center Inc. and other NEAC Medical Exams Center Inc. logos, trade names, trade dress, product and service names are proprietary to NEAC Medical Exams Center Inc., its subsidiaries and affiliates (collectively the "Marks"). In addition, NEAC Medical Exams Center Inc. may license from third parties the rights to use their Marks on its products ("Third Party Marks"). You agree not to display or use either the Marks or the Third Party Marks in any manner. <br><br>
                                        <b>General Information</b><br><br>
                                        The Terms and Conditions constitute the entire agreement between you and NEAC Medical Exams Center Inc. and govern your use of the Site, superseding any prior agreements between you and NEAC Medical Exams Center Inc.. The Terms and Conditions and the relationship between you and NEAC Medical Exams Center Inc. shall be governed by the laws of the State of Maryland without regard to its conflict of law provisions. You and NEAC Medical Exams Center Inc. agree to submit to the personal and exclusive jurisdiction of the courts located within the State of Maryland. The failure of NEAC Medical Exams Center Inc. to exercise or enforce any right or provision of the Terms and Conditions shall not constitute a waiver of such right or provision. If any provision of the Terms and Conditions is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties' intentions as reflected in the provision, and the other provisions of the Terms and Conditions remain in full force and effect. You agree that regardless of any statute or law to the contrary, you must file any claim or cause of action arising out of or related to your use of the Site or the Terms and Conditions within one (1) year after such claim or cause of action arose or be forever barred. The section titles in the Terms and Conditions are for convenience only and have no legal or contractual effect. <br><br>
                                        <b>Disclaimer </b><br><br>
                                        The information contained in this website is offered for informational purposes and is not to be construed as an endorsement or representation of the capability of any Licensing Consultant or Processing Officer to perform work on a satisfactory basis. Instead, NEAC Medical Exams Center Inc. represents that, to the best of its knowledge, the Licensing Officers listed have met the requirements for NEAC Medical Exams Center Inc. Certification by successfully passing a qualifying examination that demonstrates their awareness and understanding of “licensing processes".<br><br>
                                        NEAC Medical Exams Center Inc. makes reasonable efforts to maintain current and accurate information on this website; however, third party products, services and technologies that are featured on the website are neither tested nor endorsed by NEAC Medical Exams Center Inc.. All information about these third party offerings is provided only to alert users to trends in the field of "licensing process" and NEAC Medical Exams Center Inc. makes no representations or guarantees as to their currency, efficacy or quality. All information about third party offerings is subject to change without prior or timely notice to NEAC Medical Exams Center Inc. and NEAC Medical Exams Center Inc. is under no obligation to update this website regarding such changes. You should not rely upon any information contained in this website without making further inquiries as to the status of listed professionals and third party offerings. <br><br>
                                        NEAC Medical Exams Center Inc. Advisory Board members, and NEAC Medical Exams Center Inc. Certification Board members, act in an advisory capacity only and are not responsible or liable for decisions or actions of NEAC Medical Exams Center Inc.. <br><br>
                                        We encourage any interested party to contact the NEAC Medical Exams Center Inc. office to receive pertinent information and material facts about the organization and its activities. <br><br>
                                        <ul>
                                            Registration and Password. <br>
                                            You are responsible for maintaining the confidentiality of your N.E.A.C Account, N.E.A.C <br><br>
                                        </ul>
                                        DISCLAIMERS AND LIMITATIONS OF LIABILITY<br>
                                        YOU EXPRESSLY UNDERSTAND AND AGREE THAT: <br><br>
                                        (a) THE SITE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. NEAC Medical Exams Center Inc. EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, WITH RESPECT TO THE SITE, LICENSED CONTENT OR INFORMATION REGARDING PERSONS OR BUSINESS ENTITIES CERTIFIED BY NEAC Medical Exams Center Inc., INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT AND NONINTERFERENCE WITH YOUR ENJOYMENT OF THE SITE. <br><br>
                                        (b) NEAC Medical Exams Center Inc. MAKES NO WARRANTY THAT (i) THE SITE WILL MEET YOUR REQUIREMENTS, (ii) THE SITE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, (iii) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SITE WILL BE ACCURATE OR RELIABLE, AND (iv) THE QUALITY OF ANY PRODUCTS OR SERVICES WILL MEET YOUR EXPECTATIONS. <br><br>
                                        (c) ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SITE IS DONE AT YOUR OWN DISCRETION AND RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL. <br><br>
                                        (d) NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM NEAC Medical Exams Center Inc. OR THROUGH OR FROM THE SITE SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THE TERMS AND CONDITIONS. <br><br>
                                        YOU EXPRESSLY UNDERSTAND AND AGREE THAT NEAC Medical Exams Center Inc. SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF NEAC Medical Exams Center Inc. HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM: (i) THE USE OR THE INABILITY TO USE THE SITE; (ii) THE COST OF PROCUREMENT OF SUBSTITUTE PRODUCTS AND SERVICES RESULTING FROM ANY DATA INFORMATION OR SERVICES PURCHASED OR OBTAINED OR MESSAGES RECEIVED OR TRANSACTIONS ENTERED INTO THROUGH OR FROM THE SITE; (iii) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; (iv) STATEMENTS OR CONDUCT BY YOU OR ANY THIRD PARTY ON THE SITE; OR (v) ANY OTHER MATTER RELATING TO THE SITE. TO THE EXTENT THAT SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SOME OF THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU. <br><br>
                                        THE COMPANY DOES NOT WARRANT THAT ANY N.E.A.C SITE WILL OPERATE ERROR-FREE OR THAT ANY N.E.A.C SITE AND ITS SERVERS ARE FREE OF COMPUTER VIRUSES OR OTHER HARMFUL MECHANISMS. IF YOUR USE OF ANY N.E.A.C SITE OR THE N.E.A.C CONTENT RESULTS IN THE NEED FOR SERVICING OR REPLACING EQUIPMENT OR DATA, THE COMPANY IS NOT RESPONSIBLE FOR THOSE COSTS. THE N.E.A.C SITES AND N.E.A.C CONTENT ARE PROVIDED ON AN "AS IS" BASIS WITHOUT ANY WARRANTIES OF ANY KIND. THE COMPANY, TO THE FULLEST EXTENT PERMITTED BY LAW, DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS OR IMPLIED, INCLUDING THE WARRANTY OF MERCHANTABILITY, FITNESS FOR PARTICULAR PURPOSE AND NON-INFRINGEMENT. THE COMPANY MAKES NO WARRANTIES ABOUT THE ACCURACY, RELIABILITY, COMPLETENESS, OR TIMELINESS OF THE N.E.A.C CONTENT, SERVICES, SOFTWARE, TEXT, GRAPHICS, AND LINKS. <br><br>
                                        Disclaimer of Consequential Damages. <br>
                                        <ul>
                                            IN NO EVENT SHALL THE COMPANY, ITS SUPPLIERS, OR ANY THIRD PARTIES MENTIONED ON ANY N.E.A.C SITE BE LIABLE FOR ANY DAMAGES WHATSOEVER (INCLUDING, WITHOUT LIMITATION, INCIDENTAL AND CONSEQUENTIAL DAMAGES, LOST PROFITS, OR DAMAGES RESULTING FROM LOST DATA OR BUSINESS INTERRUPTION) RESULTING FROM THE USE OR INABILITY TO USE ANY N.E.A.C SITE AND THE N.E.A.C CONTENT, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT THE COMPANY IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
                                        </ul>
                                        <br>
                                        Limitation of Liability. <br>
                                        <ul>
                                            N.E.A.C'S MAXIMUM LIABILITY ARISING OUT OF OR IN CONNECTION WITH ANY N.E.A.C SITE OR YOUR USE OF THE N.E.A.C CONTENT, REGARDLESS OF THE CAUSE OF ACTION (WHETHER IN CONTRACT, TORT, BREACH OF WARRANTY OR OTHERWISE), WILL NOT EXCEED $100. 
                                        </ul>
                                        <br>
                                        I understand N.E.A.C Services will facilitate my exam application processing which will ensure a more safer, 
                                        <ul>reliable and faster processing. However,  N.E.A.C can not be hold responsible for the loss of applications, money drafts, finger print cards or any other items collected or mailed to complete the application process, from slow processing or not processing of the documents by State Boards or the lost of documents in mail. N.E.A.C is also not responsible from not correctly filled out applications and wrong information provided in the applications. I, the undersigned, voluntarily make and grant this Waiver of Liability and Assumption of Risk in favor of N.E.A.C as partial consideration (in addition to monies paid to the N.E.A.C) for the opportunity to use the facilities, equipment, materials and/or other assets of the N.E.A.C to process my exam application(s); and/or to receive assistance, training, guidance and/or instructions from the personnel of the N.E.A.C, I hereby waive and release any and all claims whether in contract or for personal damage, damages, losses and delays. Collected Fees are non refundable. I have read, understood and accepted above terms. I would like N.E.A.C to assist me to process my exam application. </ul>
                                        <br>
                                        Links to Other Sites. <br><br>
                                        <ul>
                                            medexamcenter.com and certain other N.E.A.C Sites contain links to third party web sites. These links are provided solely as a convenience to You and not as an endorsement by the Company of the contents on such third-party Web sites. The Company is not responsible for the content of linked third-party sites and does not make any representations regarding the content or accuracy of materials on such third party Web sites. If You decide to access linked third-party Web sites, You do so at your own risk. 
                                        </ul>
                                        <br>
                                        No Resale or Unauthorized Commercial Use. <br><br>
                                        <ul>
                                            You agree not to resell or assign your rights or obligations under these Terms of Use. You also agree not to make any unauthorized commercial use of any N.E.A.C Site. 
                                        </ul>
                                        Indemnity. <br><br>
                                        <ul>
                                            You agree to defend, indemnify, and hold harmless the Company, its affiliates, and their respective officers, directors, employees and agents, from and against any claims, actions or demands, including without limitation reasonable legal and accounting fees, alleging or resulting from (i) any User Content or other material You provide to any N.E.A.C Site, (ii) your use of any N.E.A.C Content, or (iii) your breach of the terms of these Terms of Use. The Company shall provide notice to You promptly of any such claim, suit, or proceeding. 
                                        </ul>
                                        <br>
                                        General. <br><br>
                                        The Company makes no claims that the N.E.A.C Content may be lawfully viewed or accessed outside of the United States. Access to the N.E.A.C Content may not be legal by certain persons or in certain countries. If You access a medexamcenter.com or other U.S.-based N.E.A.C Sites from outside of the United States, You do so at your own risk and are responsible for compliance with the laws of your jurisdiction. These Terms of Use are governed by the internal substantive laws of the Seattle, WA, without respect to its conflict of laws principles. Jurisdiction for any claims arising under this agreement shall lie exclusively with the state or federal courts within Seattle, WA. If any provision of these Terms of Use are found to be invalid by any court having competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of these Terms of Use , which shall remain in full force and effect. No waiver of any term of these Terms of Use shall be deemed a further or continuing waiver of such term or any other term. Except as expressly provided in an additional agreement, additional terms of use for areas of medexamcenter.com, a particular "Legal Notice," or Software License or material on particular Web pages, these Terms of Use constitute the entire agreement between You and the Company with respect to the use of medexamcenter.com. No changes to these Terms of Use shall be made except by a revised posting on this page. <br><br>
                                        Additional Terms of Use. <br><br>
                                        <ul>
                                            Certain areas of medexamcenter.com and the other N.E.A.C Sites are subject to additional terms of use. By using such areas, or any part thereof, You agree to be bound by the additional terms of use applicable to such areas. 
                                        </ul>
                                        <br>
                                        N.E.A.C Learning. <br><br>
                                        <ul>
                                            N.E.A.C represents and offers various services of training providers, but does not provide the learning offered under N.E.A.C Learning. Unfortunately, from time to time training classes are canceled or changed due to a variety of reasons, including under enrollment, course instructor shortages, re-allocation of learning resources and other logistical problems. While N.E.A.C will work with You to help You contact your Learning Provider (see Learning Provider Index page), class changes and cancellations are not within N.E.A.C's control. Accordingly, N.E.A.C is not responsible for any loss, damage, liability, expense or other problem or cost that You may incur or that may arise as a result of any class, the instruction received therein, your class being canceled, or as a result of, or any change in, the subject matter, location or time of the class, or change in the instructor, facilities or equipment used in the class. 
                                        </ul>
                                        <br>
                                        Term and Termination <br><br>
                                        <ul>
                                            These Terms of Use will remain in full force and effect while You are a User of medexamcenter.com at any level. The Company reserves the right, at its sole discretion, to pursue all of its legal remedies, including but not limited to deletion of your User Content from medexamcenter.com and the other N.E.A.C Sites and immediate termination of your registration with or ability to access medexamcenter.com and the other N.E.A.C Sites and/or any other services provided to You by the Company, upon any breach by You of these Terms of Use or if the Company is unable to verify or authenticate any information You submit to medexamcenter.com or other N.E.A.C Site registration. Even after You are no longer a User of medexamcenter.com, certain provisions of these Terms of Use will remain in effect, including Sections 2, 6, 8(c), 11 through 22, inclusive.
                                        </ul>
                                        <br>
                                        <b>Violations</b>
                                        Please report any violations of the Terms and Conditions to our customer service.

                                    </td>
                                    </tr>
                                </tbody>
                            </table>
                            <p><strong>DATA PRIVACY CONSENT/ AGREEMENT<br></strong></p>
                            <table align="left" cellpadding="0" cellspacing="0" hspace="0" vspace="0">
                                <tbody>
                                    <tr>
                                    <td align="left" valign="top">
                                        <p>The NEAC Medical Exams Application Center Inc. (hereinafter, the "Company") recognizes its responsibilities under the Republic Act No. 10173 (Act), also known as the Data Privacy Act of 2012, with respect to the data it collects, records, organizes, updates, uses, consolidates or destructs from its clients/applicants The personal data obtained from application forms and other means is entered and stored within the Company's authorized information and communications system and will only be accessed by the Company's authorized personnel. The Company has instituted appropriate organizational, technical and physical security measures to ensure the protection of its clients/applicants' personal data.</p>
                                        <p>Furthermore, the information collected and stored in the portal shall only be used for the following purposes:</p>
                                        <ol>
                                            <li>Processing and reporting of documents related to the application of the clients with related institution under certain conditions as required by law.</li>
                                            <li>Activities pertaining to establishing relations with the applicants; and/or</li>
                                            <li>Such other legitimate business purposes.</li>
                                        </ol>
                                        <p>The Company shall not disclose the client's /applicant's personal information without his/her consent and shall retain this information over a period of ten years for legitimate purposes only.</p>
                                        <strong>
                                            <p>APPLICANT/CLIENT'S CONSENT:</p>
                                        </strong>
                                        <p>I have read the Company's Data Privacy Statement and express my consent for the Company to collect, record, organize, update or modify, retrieve, consult, use, consolidate, block, erase or destruct my personal data as part of my information. </p>
                                        <p>I hereby affirm my right to be informed, object to processing, access and rectify, suspend or withdraw my personal data, and be indemnified in case of damages pursuant to the provisions of the Republic Act No. 10173 of the Philippines, Data Privacy Act of 2012 and its corresponding Implementing Rules and Regulations. </p>
                                        <p>I also acknowledge and warrant that I have acquired the consent from all parties relevant to this consent and hold free and harmless and indemnify NEAC from any complaint, suit, or damages which any party may file or claim in relation to my consent.</p>
                                    </td>
                                    </tr>
                                </tbody>
                            </table>
                            
                        </div>
                        <div class="modal-footer">
                            <a href="#" class="agree-btn btn btn-sm btn-primary pl-3 pr-3">Agree</a>
                        </div>
                        </div>
                    </div>